### ISSUE TITLE
Failed while trying to get the login code

### ISSUE THREAD

**Issue by thomasmdickinson** [afk-mario/federike#27]
### Steps to reproduce the problem

Attempting to authorize with my account (@tom@labyrinth.social)

### Expected behaviour

Should have authorized

### Actual behaviour

Got error: Error: url.startsWith is not a function. (In 'url.startsWith('data:')', 'url.startsWith' is undefined)

### Detailed description

When attempting to log in with my account (@tom@labyrinth.social) I get this error message:

Error: url.startsWith is not a function. (In 'url.startsWith('data:')', 'url.startsWith' is undefined)

![CleanShot 2022-12-18 at 07 50 54](https://user-images.githubusercontent.com/11141120/208299443-2720a0e2-ffbd-4944-b60b-796fcfe90e60.png)

### Specifications

Federike V.0.1.4

My instance is running the Hometown fork of Mastodon, so maybe that's the issue? The current version is up to date with Mastodon v3.5.5 but not 4.x

**Comment by afk-mario** [comment]
@thomasmdickinson I just tried with my instance which is also based on hometown and same version and it worked, it seems like the function [`startsWidth`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith) that one of the dependencies is using, is not supported on your browser. Could you share which browser are you using? and maybe trying in a different one.

I also pushed a new version `0.1.5` with some poly fill code in hopes that that helps, let me know if the issue is fixed!

**Comment by thomasmdickinson** [comment]
I'm on Mac OS 13.0. It's still not working on Safari 16.1 but it now works in Chrome. Thanks!
